# Generated by Django 3.1.7 on 2021-03-11 10:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(unique=True, verbose_name='Zeit & Datum')),
                ('reminded_next', models.BooleanField(default=False)),
                ('reminded_rate', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('active', models.BooleanField(default=True)),
                ('dep', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WWEvents.department', verbose_name='Department')),
            ],
        ),
        migrations.CreateModel(
            name='EventRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Anonymous', max_length=50)),
                ('sausage_rating', models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Bewertung Würste')),
                ('bretzel_rating', models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Bewertung Bretzen')),
                ('mustard_rating', models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Bewertung Senf')),
                ('orga_rating', models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Bewertung Organisation')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WWEvents.event')),
            ],
        ),
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sausages', models.FloatField(default=2, verbose_name='Anz. Würste')),
                ('bretzels', models.FloatField(default=2, verbose_name='Anz. Brezen')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WWEvents.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WWEvents.user')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WWEvents.user'),
        ),
        migrations.AddField(
            model_name='event',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WWEvents.room'),
        ),
    ]
